image: 'node:14.17.6'
stages:
  - test
  - publish
build:
  stage: test
  script:
    - npm install --frozen-lockfile
    - npm run build
lint:
  stage: test
  script:
    - npm install --frozen-lockfile
    - npm run ci:lint
    - npm run ci:prettier
can-publish:
  stage: test
  script:
    - npm install -g can-npm-publish
    - can-npm-publish
  only:
    - master
publish-production:
  stage: publish
  script:
    - touch ~/.npmrc
    - 'echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" >> ~/.npmrc'
    - 'echo "@bitbank:registry=https://registry.npmjs.org" >> ~/.npmrc'
    - npm install --frozen-lockfile
    - npm run prepare
    - npm publish --access=public
  only:
    - production
