version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.17.6
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  lint:
    docker:
      - image: circleci/node:14.17.6
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run ci:lint
      - run: npm run ci:prettier

  test:
    docker:
      - image: circleci/node:14.17.6
      - image: bitbankinc/mock-bitbankcc
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD

    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: NODE_ENV=testing npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build
      - test:
          context: org-global
